import type { Metadata } from "next";
import { Open_Sans, Nunito_Sans } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/features/components/shared/NavBar";
import TopBar from "@/features/components/shared/TopBar";
import Footer from "@/features/components/shared/Footer";
import ScrollToTop from "@/features/components/shared/ScrollToTop";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${nunitoSans.variable} antialiased`}
      >
        <TopBar />
        <Navbar />
        <ScrollToTop />
        {children}
        <Footer />
      </body>
    </html>
  );
}
